### PR TITLE
Ignore library files, improve pre-commit.

### PR DESCRIPTION
**Pull request by RyanFleck**

### CODE REVIEW

**Comment by RyanFleck** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Bellboy-Capstone/System/pullRequest?prid=6308317&bid=20512494)

**Comment by RyanFleck** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 8
- Added 6
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Bellboy-Capstone/System/pullRequest?prid=6308317&bid=20512494)

**Comment by RyanFleck** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Bellboy-Capstone/System/pullRequest?prid=6308317&bid=20512494)

**Review by yozohu — APPROVED** [review]

**Comment by RyanFleck** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Bellboy-Capstone/System/pullRequest?prid=6308317&bid=20512494)

**Pull request merged**
